package gov.polisen.ainappen;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * The meaning of this class is to bypass a constraint in ORMLite.
 * It's not a pretty solution, but ORMLite does not support composite 
 * primary keys, and neither can a field be autogenerated without being
 * the primary key. This class helps bypassing that constraint for the "Case" class.
 * @author Joakim
 *
 */
@DatabaseTable(tableName = "mappointids")
public class LocalMapPointID {
	@DatabaseField(generatedId = true)
	private int localMapPointID;

	public LocalMapPointID(int localMapPointID){
		this.localMapPointID = localMapPointID;
	}
	public LocalMapPointID(){
		//needed for ORMLite
	}
	public int getLocalObstacleID(){
		return this.localMapPointID;
	}
	public void setLocalObstacleID(int localMapPointID){
		this.localMapPointID = localMapPointID;
	}
}